### PR TITLE
Use sbt-build-seed to simplify release and development

### PR DESCRIPTION
**Pull request by fedgehog**
Among other stuff does proper cross release and publishing

### CODE REVIEW

**Comment by DandyDev** [comment]
Wouldn't it make more sense to move sbt-build-seed to Github if you want to use it in akka-rabbitmq? Now you're asking people that use this library to trust a non-open source component...

**Comment by fedgehog** [comment]
Source code is opened and can be accessed 
http://nexus.thenewmotion.com/content/groups/public/com/thenewmotion/sbt-build-seed_2.10_0.13/<version>/

However it is hosted on our Nexus, that's why resolver needed.

**Comment by fedgehog** [comment]
Put sbt-build-seed to GH under https://github.com/thenewmotion/sbt-build-seed, so now it is open for collaboration.

**Comment by DandyDev** [comment]
Great! :+1:

**Pull request merged**
